name: mobile_api
description: Web tasarım projesi (PHP backend Dart frontend)

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  fluttertoast: ^8.0.9
  crypto: ^3.0.2
  cached_network_image: ^3.2.1
  shimmer_animation: ^2.1.0+1
  bottom_navy_bar: ^6.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/image/